name: Build and Deploy to IIS

on:
  push:
    branches:
      - master   

jobs:
  build-and-deploy:
    runs-on: self-hosted   

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'


      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o .\publish


      - name: Stop IIS
        run: iisreset /stop

      - name: Deploy to IIS (copy files)
        run: |
        
          xcopy /s /y .\publish\* "D:\Hien\publish-demo"

      - name: Start IIS
        run: iisreset /start